# Generated by Django 5.0.1 on 2026-01-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DEALING", "Dealing"),
                            ("LOOKING_FOR_DRIVER", "Looking for Driver"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DEALING",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "delivery_handler",
                    models.CharField(
                        choices=[
                            ("SYSTEM_DRIVER", "System Driver"),
                            ("SUPPLIER", "Supplier (3rd Party)"),
                            ("SELLER", "Seller (3rd Party)"),
                        ],
                        default="SYSTEM_DRIVER",
                        help_text="Who will handle the delivery: System driver, Supplier (3rd party), or Seller (3rd party)",
                        max_length=20,
                        verbose_name="Delivery Handler",
                    ),
                ),
                (
                    "delivery_cost_split",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Percentage of delivery cost paid by supplier when using system driver (0-100). 0=seller pays all, 100=supplier pays all, 50=split equally. Only used when delivery_handler is SYSTEM_DRIVER.",
                        verbose_name="Delivery Cost Split (%)",
                    ),
                ),
                (
                    "delivery_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of deliveries planned for this deal. For example, 200kg of onions can be delivered in 3 separate deliveries. This is the planned count, not the actual count.",
                        verbose_name="Delivery Count",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
                "db_table": "deals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal Item",
                "verbose_name_plural": "Deal Items",
                "db_table": "deal_items",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier_share",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Percentage of delivery owned by supplier (0-100). Remaining percentage belongs to seller.",
                        verbose_name="Supplier Share (%)",
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True,
                        help_text="Driver name for 3rd party drivers (when driver_profile is null)",
                        max_length=255,
                        null=True,
                        verbose_name="Driver Name",
                    ),
                ),
                (
                    "driver_phone",
                    models.CharField(
                        blank=True,
                        help_text="Driver phone number",
                        max_length=20,
                        null=True,
                        verbose_name="Driver Phone",
                    ),
                ),
                (
                    "driver_vehicle_type",
                    models.CharField(
                        blank=True,
                        help_text="Driver vehicle type",
                        max_length=20,
                        null=True,
                        verbose_name="Driver Vehicle Type",
                    ),
                ),
                (
                    "driver_vehicle_plate",
                    models.CharField(
                        blank=True,
                        help_text="Driver vehicle plate number",
                        max_length=20,
                        null=True,
                        verbose_name="Driver Vehicle Plate",
                    ),
                ),
                (
                    "driver_license_number",
                    models.CharField(
                        blank=True,
                        help_text="Driver license number",
                        max_length=50,
                        null=True,
                        verbose_name="Driver License Number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ESTIMATED", "Estimated"),
                            ("CONFIRMED", "Confirmed"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ESTIMATED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="Delivery Address")),
                (
                    "delivery_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Delivery Note"
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
                "db_table": "deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
            ],
            options={
                "verbose_name": "Delivery Item",
                "verbose_name_plural": "Delivery Items",
                "db_table": "delivery_items",
            },
        ),
        migrations.CreateModel(
            name="RequestToDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price offered by supplier/seller to driver",
                        max_digits=10,
                        verbose_name="Requested Price",
                    ),
                ),
                (
                    "driver_proposed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price proposed by driver (counter offer)",
                        max_digits=10,
                        null=True,
                        verbose_name="Driver Proposed Price",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final agreed price when request is accepted",
                        max_digits=10,
                        null=True,
                        verbose_name="Final Price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DRIVER_PROPOSED", "Driver Proposed"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("COUNTER_OFFERED", "Counter Offered"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "supplier_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Supplier has approved the price",
                        verbose_name="Supplier Approved",
                    ),
                ),
                (
                    "seller_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Seller has approved the price",
                        verbose_name="Seller Approved",
                    ),
                ),
                (
                    "driver_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Driver has approved the price",
                        verbose_name="Driver Approved",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request to Driver",
                "verbose_name_plural": "Requests to Driver",
                "db_table": "requests_to_driver",
                "ordering": ["-created_at"],
            },
        ),
    ]
