# Generated by Django 5.0.1 on 2026-01-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0002_remove_orderitem_order_remove_orderitem_product_and_more"),
        ("users", "0002_user_role_alter_user_email_driverprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMED", "Confirmed"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                    ("PICKED_UP", "Picked Up"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="CONFIRMED",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DEALING", "Dealing"),
                            ("LOOKING_FOR_DRIVER", "Looking for Driver"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DEALING",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="Delivery Address")),
                (
                    "delivery_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Delivery Note"
                    ),
                ),
                (
                    "cost_split",
                    models.BooleanField(
                        default=False,
                        help_text="If True, both supplier and seller can request drivers (costs split)",
                        verbose_name="Cost Split",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="users.driverprofile",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deal",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="users.sellerprofile",
                        verbose_name="Seller",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="users.supplierprofile",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
                "db_table": "deals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.deal",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal Item",
                "verbose_name_plural": "Deal Items",
                "db_table": "deal_items",
            },
        ),
    ]
