# Generated by Django 5.0.1 on 2026-01-28 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="System driver assigned to this deal (only used when delivery_handler is SYSTEM_DRIVER)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="users.driverprofile",
                verbose_name="Driver",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="users.supplierprofile",
                verbose_name="Supplier",
            ),
        ),
        migrations.AddField(
            model_name="dealitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="dealitem",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.deal",
            ),
        ),
        migrations.AddField(
            model_name="dealitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="deal",
            field=models.ForeignKey(
                help_text="The deal this delivery was created from. Delivery is always linked to a deal.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="orders.deal",
                verbose_name="Deal",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="driver_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="System driver profile if driver is registered in system. If null, use manual driver fields for 3rd party drivers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="users.driverprofile",
                verbose_name="Driver Profile",
            ),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="deal_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_items",
                to="orders.dealitem",
                verbose_name="Deal Item",
            ),
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.delivery",
            ),
        ),
        migrations.AddField(
            model_name="requesttodriver",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="requesttodriver",
            name="deal",
            field=models.ForeignKey(
                help_text="The deal this request is for. Only valid for SYSTEM_DRIVER delivery_handler.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_requests",
                to="orders.deal",
                verbose_name="Deal",
            ),
        ),
        migrations.AddField(
            model_name="requesttodriver",
            name="driver",
            field=models.ForeignKey(
                help_text="Driver who received this request",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_requests",
                to="users.driverprofile",
                verbose_name="Driver",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requesttodriver",
            unique_together={("deal", "driver")},
        ),
    ]
