# Generated by Django migration – Deal approval fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="seller_approved",
            field=models.BooleanField(
                default=False,
                help_text="Seller has approved the current deal/items. Cleared when supplier edits deal or items.",
                verbose_name="Seller Approved",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="supplier_approved",
            field=models.BooleanField(
                default=False,
                help_text="Supplier has approved the current deal/items. Cleared when seller edits deal or items.",
                verbose_name="Supplier Approved",
            ),
        ),
    ]
