# Generated by Django 5.0.1 on 2026-01-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_deal_order_remove_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                help_text="The deal this delivery was created from (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="orders.deal",
                verbose_name="Deal",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="delivery",
            field=models.OneToOneField(
                blank=True,
                help_text="Primary delivery created from this deal (OneToOne relationship)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deal_one_to_one",
                to="orders.delivery",
                verbose_name="Delivery",
            ),
        ),
    ]
