# Generated by Django 5.0.1 on 2026-01-28 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_deal_seller_approved_supplier_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="driver",
        ),
    ]
