# Generated by Django 5.0.1 on 2026-01-29 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_deal_driver"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dealitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Deal Item",
                "verbose_name_plural": "Deal Items",
            },
        ),
    ]
