# Generated by Django 5.0.1 on 2026-01-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_delivery_deal_alter_deal_delivery"),
        ("users", "0002_user_role_alter_user_email_driverprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="supplier",
        ),
        migrations.AddField(
            model_name="delivery",
            name="driver_name",
            field=models.CharField(
                blank=True,
                help_text="Driver name if not from system",
                max_length=255,
                null=True,
                verbose_name="Driver Name",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="driver_phone",
            field=models.CharField(
                blank=True,
                help_text="Driver phone if not from system",
                max_length=20,
                null=True,
                verbose_name="Driver Phone",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="driver_vehicle_plate",
            field=models.CharField(
                blank=True,
                help_text="Driver vehicle plate if not from system",
                max_length=20,
                null=True,
                verbose_name="Driver Vehicle Plate",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="driver_vehicle_type",
            field=models.CharField(
                blank=True,
                help_text="Driver vehicle type if not from system",
                max_length=20,
                null=True,
                verbose_name="Driver Vehicle Type",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="System driver if available, otherwise null for external/manual driver",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="users.driverprofile",
                verbose_name="Driver",
            ),
        ),
    ]
