# Generated by Django 5.0.1 on 2026-01-24 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_delivery_seller_remove_delivery_supplier_and_more"),
        ("users", "0002_user_role_alter_user_email_driverprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="driver",
        ),
        migrations.AddField(
            model_name="delivery",
            name="driver_license_number",
            field=models.CharField(
                blank=True,
                help_text="Driver license number",
                max_length=50,
                null=True,
                verbose_name="Driver License Number",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="driver_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="System driver profile if driver is registered in system",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="users.driverprofile",
                verbose_name="Driver Profile",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="driver_name",
            field=models.CharField(
                blank=True,
                help_text="Driver name (required if driver_profile is null and delivery has a driver)",
                max_length=255,
                null=True,
                verbose_name="Driver Name",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="driver_phone",
            field=models.CharField(
                blank=True,
                help_text="Driver phone number",
                max_length=20,
                null=True,
                verbose_name="Driver Phone",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="driver_vehicle_plate",
            field=models.CharField(
                blank=True,
                help_text="Driver vehicle plate number",
                max_length=20,
                null=True,
                verbose_name="Driver Vehicle Plate",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="driver_vehicle_type",
            field=models.CharField(
                blank=True,
                help_text="Driver vehicle type",
                max_length=20,
                null=True,
                verbose_name="Driver Vehicle Type",
            ),
        ),
    ]
