# Generated by Django 5.0.1 on 2026-01-24 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_remove_delivery_driver_and_more"),
        ("users", "0002_user_role_alter_user_email_driverprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="delivery",
        ),
        migrations.AddField(
            model_name="deal",
            name="delivery_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of deliveries created from this deal",
                verbose_name="Delivery Count",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="Seller for standalone deliveries (required if deal is null)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standalone_deliveries",
                to="users.sellerprofile",
                verbose_name="Seller",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier for standalone deliveries (required if deal is null)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standalone_deliveries",
                to="users.supplierprofile",
                verbose_name="Supplier",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="supplier_share",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Percentage of delivery owned by supplier (0-100). Only used when delivery is from a deal.",
                verbose_name="Supplier Share (%)",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                help_text="The deal this delivery was created from (if any). If null, this is a standalone delivery.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="orders.deal",
                verbose_name="Deal",
            ),
        ),
    ]
