# Generated by Django 5.0.1 on 2026-01-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_delivery_delivery_cost_split"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="delivery_cost_split",
        ),
        migrations.AddField(
            model_name="deal",
            name="delivery_cost_split",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Percentage of delivery cost paid by supplier when using system driver (0-100). 0=seller pays all, 100=supplier pays all, 50=split equally. Only used when delivery_handler is SYSTEM_DRIVER.",
                verbose_name="Delivery Cost Split (%)",
            ),
        ),
    ]
