# Generated by Django 5.0.1 on 2026-01-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_alter_deal_delivery_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="delivery_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of deliveries planned for this deal. For example, 200kg of onions can be delivered in 3 separate deliveries. This is the planned count, not the actual count.",
                verbose_name="Delivery Count",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("ESTIMATED", "Estimated"),
                    ("CONFIRMED", "Confirmed"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                    ("PICKED_UP", "Picked Up"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="CONFIRMED",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
