# Generated by Django 5.0.1 on 2026-01-24 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0017_deal_created_by_dealitem_created_by_and_more"),
        ("users", "0003_driverprofile_created_by_sellerprofile_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestToDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price offered by supplier/seller to driver",
                        max_digits=10,
                        verbose_name="Requested Price",
                    ),
                ),
                (
                    "driver_proposed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price proposed by driver (counter offer)",
                        max_digits=10,
                        null=True,
                        verbose_name="Driver Proposed Price",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final agreed price when request is accepted",
                        max_digits=10,
                        null=True,
                        verbose_name="Final Price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DRIVER_PROPOSED", "Driver Proposed"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("COUNTER_OFFERED", "Counter Offered"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "supplier_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Supplier has approved the price",
                        verbose_name="Supplier Approved",
                    ),
                ),
                (
                    "seller_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Seller has approved the price",
                        verbose_name="Seller Approved",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        help_text="The deal this request is for. Only valid for SYSTEM_DRIVER delivery_handler.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_requests",
                        to="orders.deal",
                        verbose_name="Deal",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Driver who received this request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_requests",
                        to="users.driverprofile",
                        verbose_name="Driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request to Driver",
                "verbose_name_plural": "Requests to Driver",
                "db_table": "requests_to_driver",
                "ordering": ["-created_at"],
                "unique_together": {("deal", "driver")},
            },
        ),
    ]
