# Generated by Django 5.0.1 on 2026-01-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_driverprofile_created_by_sellerprofile_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driverprofile",
            options={
                "verbose_name": "Driver profile",
                "verbose_name_plural": "Driver profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="sellerprofile",
            options={
                "verbose_name": "Seller profile",
                "verbose_name_plural": "Seller profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="supplierprofile",
            options={
                "verbose_name": "Supplier profile",
                "verbose_name_plural": "Supplier profiles",
            },
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Available"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="license_number",
            field=models.CharField(max_length=50, verbose_name="License number"),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_plate",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="License plate"
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("MOTORCYCLE", "Motorcycle"),
                    ("CAR", "Car"),
                    ("VAN", "Van"),
                    ("TRUCK", "Truck"),
                ],
                default="CAR",
                max_length=20,
                verbose_name="Vehicle type",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="business_name",
            field=models.CharField(max_length=255, verbose_name="Business name"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="business_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Business type"
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="tax_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Tax number"
            ),
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Company name"),
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="tax_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Tax number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPPLIER", "Supplier"),
                    ("SELLER", "Seller"),
                    ("DRIVER", "Driver"),
                ],
                default="SELLER",
                max_length=20,
            ),
        ),
    ]
