# Generated by Django 5.0.1 on 2026-01-24 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_remove_deal_delivery_deal_delivery_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="delivery_note",
        ),
    ]
