# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


def delete_null_deal_deliveries(apps, schema_editor):
    """Delete deliveries with null deal (standalone deliveries)"""
    Delivery = apps.get_model('orders', 'Delivery')
    Delivery.objects.filter(deal__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_deal_delivery_address_and_more'),
    ]

    operations = [
        # First, delete any deliveries with null deal
        migrations.RunPython(delete_null_deal_deliveries, migrations.RunPython.noop),
        # Remove supplier and seller fields
        migrations.RemoveField(
            model_name='delivery',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='seller',
        ),
        # Make deal required (non-nullable)
        migrations.AlterField(
            model_name='delivery',
            name='deal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='deliveries',
                to='orders.deal',
                verbose_name='Deal',
                help_text='The deal this delivery was created from. Delivery is always linked to a deal.'
            ),
        ),
    ]
