# Generated by Django 5.0.1 on 2026-01-24 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_auto_20260125_0102"),
        ("users", "0002_user_role_alter_user_email_driverprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="delivery_handler",
            field=models.CharField(
                choices=[
                    ("SYSTEM_DRIVER", "System Driver"),
                    ("SUPPLIER", "Supplier (3rd Party)"),
                    ("SELLER", "Seller (3rd Party)"),
                ],
                default="SYSTEM_DRIVER",
                help_text="Who will handle the delivery: System driver, Supplier (3rd party), or Seller (3rd party)",
                max_length=20,
                verbose_name="Delivery Handler",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="System driver assigned to this deal (only used when delivery_handler is SYSTEM_DRIVER)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="users.driverprofile",
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="driver_name",
            field=models.CharField(
                blank=True,
                help_text="Driver name for 3rd party drivers (when driver_profile is null)",
                max_length=255,
                null=True,
                verbose_name="Driver Name",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="driver_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="System driver profile if driver is registered in system. If null, use manual driver fields for 3rd party drivers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="users.driverprofile",
                verbose_name="Driver Profile",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="supplier_share",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Percentage of delivery owned by supplier (0-100). Remaining percentage belongs to seller.",
                verbose_name="Supplier Share (%)",
            ),
        ),
    ]
