# Generated by Django 5.0.1 on 2026-01-24 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_deal_delivery_handler_alter_deal_driver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="cost_split",
        ),
    ]
