# Generated by Django 5.0.1 on 2026-01-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_remove_delivery_delivery_cost_split_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="delivery_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of deliveries created from this deal",
                verbose_name="Delivery Count",
            ),
        ),
    ]
