# Generated by Django 5.0.1 on 2026-01-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_alter_deal_delivery_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="delivery_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of deliveries created from this deal. Default is 1 because each deal must have at least one delivery.",
                verbose_name="Delivery Count",
            ),
        ),
    ]
