# Generated by Django 5.0.1 on 2026-01-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_requesttodriver"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesttodriver",
            name="driver_approved",
            field=models.BooleanField(
                default=False,
                help_text="Driver has approved the price",
                verbose_name="Driver Approved",
            ),
        ),
    ]
